import type { Metadata } from "next";
import { Raleway, Oswald, Poppins, DM_Serif_Display } from "next/font/google";

import Toast from "@/components/Common/Toast";
import ThemeProvider from "@/Providers/ThemeProvider";

//css
import "./globals.css";
import { Container } from "./home/index.styles";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Adjust weights as needed
  variable: "--font-raleway",
  display: "swap",
});

const oswald = Oswald({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Adjust weights as needed
  variable: "--font-oswald",
  display: "swap",
});

const popins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Adjust weights as needed
  variable: "--font-poppins",
  display: "swap",
});

const dmSerif = DM_Serif_Display({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-dm-serif",
  display: "swap",
});

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=DM+Serif+Display&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${raleway.className} ${dmSerif.className}antialised ${oswald.className}antialiased ${popins.className}antialiased`}>
        <ThemeProvider>
          <Toast />
          <Container>{children}</Container>
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
