import type { Metadata } from "next";
import localFont from "next/font/local";
import { Raleway, Oswald, Poppins } from "next/font/google";

import Toast from "@/components/Common/Toast";
import ThemeProvider from "@/Providers/ThemeProvider";

//css
import "./globals.css";
import { Container } from "./home/index.styles";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Adjust weights as needed
  variable: "--font-raleway",
  display: "swap",
});

const oswald = Oswald({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Adjust weights as needed
  variable: "--font-oswald",
  display: "swap",
});

const popins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Adjust weights as needed
  variable: "--font-poppins",
  display: "swap",
});

const beautyRachela = localFont({
  src: [
    {
      path: "../../public/fonts/beauty-rachela/BeautyRachela-Regular.otf",
      weight: "400",
      style: "normal",
    },
  ],
});

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body
        className={`${raleway.className} ${beautyRachela.className}antialiased ${oswald.className}antialiased ${popins.className}antialiased`}
      >
        <ThemeProvider>
          <Toast />
          <Container>{children}</Container>
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
